# Generated by Django 5.1.2 on 2024-12-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuccer', '0007_alter_callparticipant_unique_together_callroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callroom',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='callroom',
            name='participants',
        ),
        migrations.DeleteModel(
            name='CallParticipant',
        ),
        migrations.DeleteModel(
            name='CallRoom',
        ),
    ]
