# Generated by Django 5.1.2 on 2024-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuccer', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
