# Generated by Django 5.1.2 on 2024-12-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuccer', '0010_boardmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
