# Generated by Django 5.1.2 on 2024-12-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuccer', '0011_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
